repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.0
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: golangci-lint
    - id: go-imports
    - id: go-mod-tidy
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.17.0
  hooks:
    - id: gitlint
