name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Go
      uses: actions/setup-go@v3
       
    - name: build
      run: go build . 
      
    - name: lint
      uses: golangci/golangci-lint-action@v3.2.0
      with:
        version: latest
    
    - name: test
      run: go test -v ./...

    - name: release
      uses: goreleaser/goreleaser-action@v3
      if: startsWith(github.ref, 'refs/tags/')
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
